version: "3.2"
services:
    db:
      image: postgres
      volumes:
        - db_data:/var/lib/postgresql
        - ./postgresql-dump:/docker-entrypoint-initdb.d
      restart: always
      environment: 
        POSTGRES_PASSWORD: qqqrwqeqwqeqS6
        POSTGRES_DB: express_db
      ports:
        - 3307:3306
    
    redis:
      image: "redis:alpine"
      command: ["redis-server", "--appendonly", "yes"]
      hostname: redis
      ports:
        - "6379:6379"
  
    web_app:
      restart: always
      depends_on: 
        - db
      build: ./
      command: npm start
      volumes:
        - ./src:/var/www/app/src
        - ./package.json:/var/www/app/package.json
      ports:
        - 3001:3000
        - 9229:9229

volumes: 
    db_data: {}